// Reads float_corpus.txt (one u64 bit pattern per line, hex) and
// float_expected.jsonl ({"bits","js"} per line, generated by Node's
// Number.prototype.toString), and asserts the Rust ECMAScript formatter
// agrees on every pattern.
//
// Regeneration:
//   python3 tests/gen_float_corpus.py          # in tests/
//   node tests/gen_float_expected.mjs          # in tests/
// Both files are checked in; the test fails if they are missing so a
// checkout can never silently skip the differential.
use nido_conformance_rs::num;
use std::collections::HashMap;

fn load_corpus(path: &str) -> Vec<u64> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("missing {path}: run the generator scripts first ({e})"));
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| u64::from_str_radix(l.trim(), 16).expect("bad hex in corpus"))
        .collect()
}

fn load_expected(path: &str) -> HashMap<u64, String> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("missing {path}: run node tests/gen_float_expected.mjs ({e})"));
    let mut map = HashMap::new();
    for line in text.lines() {
        if line.trim().is_empty() {
            continue;
        }
        // minimal JSON parsing: {"bits":"<hex>","js":"<str>"}
        let bits = line
            .split("\"bits\":\"")
            .nth(1)
            .expect("bad line")
            .split('"')
            .next()
            .unwrap();
        let js = line.split("\"js\":\"").nth(1).expect("bad line");
        // unescape the JSON string (only \" and \\ occur in number output)
        let mut out = String::new();
        let mut it = js.chars();
        while let Some(c) = it.next() {
            if c == '"' {
                break;
            }
            if c == '\\' {
                out.push(it.next().expect("bad escape"));
            } else {
                out.push(c);
            }
        }
        map.insert(u64::from_str_radix(bits, 16).expect("bad hex"), out);
    }
    map
}

#[test]
fn float_format_matches_js_engine() {
    let dir = env!("CARGO_MANIFEST_DIR");
    let corpus = load_corpus(&format!("{dir}/tests/float_corpus.txt"));
    let expected = load_expected(&format!("{dir}/tests/float_expected.jsonl"));
    assert_eq!(
        corpus.len(),
        expected.len(),
        "corpus and expected outputs disagree in size; regenerate both"
    );
    let mut mismatches = 0usize;
    for bits in &corpus {
        let v = f64::from_bits(*bits);
        let got = num::format_es(v);
        match expected.get(bits) {
            Some(want) if *want == got => {}
            Some(want) => {
                mismatches += 1;
                if mismatches <= 10 {
                    eprintln!("MISMATCH bits={bits:016x} js={want} rust={got}");
                }
            }
            None => panic!("bits {bits:016x} missing from expected file"),
        }
    }
    assert_eq!(
        mismatches, 0,
        "{mismatches} float formatting mismatches vs Node"
    );
}
