/**
 * MIT License
 * Copyright (c) 2026 NIDO contributors
 * See LICENSE file for details.
 *
 * manifestSignature.ts — GENERATED by scripts/sign-manifest.mjs. Do not hand-edit.
 * Detached Ed25519 signature over the canonical catalog JSON
 * (see canonicalCatalogJSON in manifestTrust.ts). Regenerate after any
 * manifest.ts change that touches a signed field.
 */
export const MANIFEST_SIGNATURE_BASE64 = "X2cldqdR2Tdk13EmFKsEbTKJauVyfueYcw5uuzMOdvm75NIB24415aaF25W41bcUelTmPbMeAoVcvtof5b2vBg==";
